[package]
name = "poc-kokkos-rs"
version = "0.1.0"
edition = "2021"

# FEATURES 

[features]
serial = []
threads = []
rayon = ["dep:rayon", "dep:atomic"]

# DEPENDENCIES

[dependencies]
cxx = "*"
cfg-if = "*"
rayon = {version = "*", optional=true}
atomic = {version = "0.5.3", optional=true}
#bytemuck = {version = "*", optional=true}

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }
rand = { version = "*", features = ["small_rng", "alloc"] }

[build-dependencies]
cxx-build = "*"

# BENCHMARKS

[[bench]]
name = "layout"
harness = false

[[bench]]
name = "view_init"
harness = false

[[bench]]
name = "view_access"
harness = false

[[bench]]
name = "mdrange_populate"
harness = false

[[bench]]
name = "feature"
harness = false
