[package]
name = "poc-kokkos-rs"
version = "0.1.0"
edition = "2021"

# FEATURES 

[features]
threads = ["dep:atomic", "dep:num_cpus"]
rayon =   ["dep:atomic", "dep:num_cpus", "dep:rayon"]
gpu =     ["dep:atomic"]

# DEPENDENCIES

[dependencies]
cxx      = "*"
cfg-if   = "*"
rayon    = {version = "*", optional=true}
atomic   = {version = "0.5.3", optional=true}
num_cpus = {version = "1.0", optional=true}
#bytemuck = {version = "*", optional=true} # needed for atomic >= 0.6.0

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }
rand      = { version = "*", features = ["small_rng", "alloc"] }

[build-dependencies]
cxx-build = "*"

# BENCHMARKS

[[bench]]
name = "layout"
harness = false

[[bench]]
name = "view_init"
harness = false

[[bench]]
name = "view_access"
harness = false

[[bench]]
name = "mdrange_populate"
harness = false

[[bench]]
name = "axpy"
harness = false

[[bench]]
name = "gemv"
harness = false
