[package]
name = "poc-kokkos-rs"
version = "0.1.0"
edition = "2021"

# DEPENDENCIES

[dependencies]
cxx = "*"

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }

[build-dependencies]
cxx-build = "*"

# BENCHMARKS

[[bench]]
name = "gemv"
harness = false

[[bench]]
name = "view_init"
harness = false

[[bench]]
name = "view_access"
harness = false
